//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Код { get; set; }
        public Nullable<int> Сотрудник { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public byte[] upsize_ts { get; set; }
    
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
