//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Код { get; set; }
        public Nullable<int> Сотрудник { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public byte[] upsize_ts { get; set; }
    
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
