//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class Документы_о_выдаче
    {
        public Документы_о_выдаче()
        {
            this.Имущество = new ObservableListSource<Имущество>();
        }
    
        public int Код { get; set; }
        public string Наименование { get; set; }
        public Nullable<int> Номер { get; set; }
        public Nullable<System.DateTime> Дата_выдачи { get; set; }
        public string Выдал { get; set; }
        public byte[] upsize_ts { get; set; }
    
        public virtual ObservableListSource<Имущество> Имущество { get; set; }
    }
}
