//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class Звания
    {
        public Звания()
        {
            this.Нормативы = new ObservableListSource<Нормативы>();
            this.Сотрудники = new ObservableListSource<Сотрудники>();
        }
    
        public int Код { get; set; }
        public string Звание { get; set; }
        public byte[] upsize_ts { get; set; }
    
        public virtual ObservableListSource<Нормативы> Нормативы { get; set; }
        public virtual ObservableListSource<Сотрудники> Сотрудники { get; set; }
    }
}
