//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class Звания
    {
        public Звания()
        {
            this.Нормативы = new ObservableListSource<Нормативы>();
            this.Сотрудники = new ObservableListSource<Сотрудники>();
        }
    
        public int Код { get; set; }
        public string Звание { get; set; }
        public byte[] upsize_ts { get; set; }
    
        public virtual ObservableListSource<Нормативы> Нормативы { get; set; }
        public virtual ObservableListSource<Сотрудники> Сотрудники { get; set; }
    }
}
