//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class Нормативы
    {
        public Нормативы()
        {
            this.Имущество = new ObservableListSource<Имущество>();
        }
    
        public int Код { get; set; }
        public Nullable<int> Форма_обеспечения { get; set; }
        public Nullable<int> Звание { get; set; }
        public Nullable<int> Предмет { get; set; }
        public Nullable<int> Количество { get; set; }
        public string Срок_службы { get; set; }
        public Nullable<decimal> Размер_компенсации { get; set; }
        public byte[] upsize_ts { get; set; }
    
        public virtual Звания Звания { get; set; }
        public virtual ObservableListSource<Имущество> Имущество { get; set; }
        public virtual Предметы Предметы { get; set; }
        public virtual ФормыОбеспечения ФормыОбеспечения { get; set; }
    }
}
