//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class Подразделения
    {
        public Подразделения()
        {
            this.Подразделения1 = new ObservableListSource<Подразделения>();
            this.Приказы = new ObservableListSource<Приказы>();
            this.Сотрудники = new ObservableListSource<Сотрудники>();
        }
    
        public int Код { get; set; }
        public string Наименование { get; set; }
        public Nullable<int> Головное_подразделение { get; set; }
        public byte[] upsize_ts { get; set; }
    
        public virtual ObservableListSource<Подразделения> Подразделения1 { get; set; }
        public virtual Подразделения Подразделения2 { get; set; }
        public virtual ObservableListSource<Приказы> Приказы { get; set; }
        public virtual ObservableListSource<Сотрудники> Сотрудники { get; set; }
    }
}
