//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class Приказы
    {
        public int Код { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public Nullable<int> Номер { get; set; }
        public string Наименование { get; set; }
        public Nullable<int> Сотрудник { get; set; }
        public Nullable<int> Подразделение { get; set; }
        public byte[] upsize_ts { get; set; }
    
        public virtual Подразделения Подразделения { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
