//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудники
    {
        public Сотрудники()
        {
            this.Users = new ObservableListSource<User>();
            this.Приказы = new ObservableListSource<Приказы>();
        }
    
        public int Код { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public Nullable<int> Рост { get; set; }
        public Nullable<int> Объем_груди { get; set; }
        public Nullable<int> Звание { get; set; }
        public Nullable<int> Подразделение { get; set; }
        public string Пол { get; set; }
        public byte[] upsize_ts { get; set; }
    
        public virtual ObservableListSource<User> Users { get; set; }
        public virtual Звания Звания { get; set; }
        public virtual Подразделения Подразделения { get; set; }
        public virtual ObservableListSource<Приказы> Приказы { get; set; }
    }
}
