//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class Справочные_значения
    {
        public int Код { get; set; }
        public Nullable<int> Справочник { get; set; }
        public string Значение { get; set; }
        public byte[] upsize_ts { get; set; }
    
        public virtual Справочники Справочники { get; set; }
    }
}
