//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class Справочники
    {
        public Справочники()
        {
            this.Справочные_значения = new ObservableListSource<Справочные_значения>();
        }
    
        public int Код { get; set; }
        public string Наименование { get; set; }
        public byte[] upsize_ts { get; set; }
    
        public virtual ObservableListSource<Справочные_значения> Справочные_значения { get; set; }
    }
}
