//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class Справочники
    {
        public Справочники()
        {
            this.Справочные_значения = new ObservableListSource<Справочные_значения>();
        }
    
        public int Код { get; set; }
        public string Наименование { get; set; }
        public byte[] upsize_ts { get; set; }
    
        public virtual ObservableListSource<Справочные_значения> Справочные_значения { get; set; }
    }
}
