//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Common
{
    using System;


    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonResources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources()
        {
        }

        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Common.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirmation.
        /// </summary>
        internal static string Confirmation_Caption
        {
            get
            {
                return ResourceManager.GetString("Confirmation_Caption", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you want to delete this {0}?.
        /// </summary>
        internal static string Confirmation_Delete
        {
            get
            {
                return ResourceManager.GetString("Confirmation_Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Click OK to reload the entity and lose unsaved changes. Click Cancel to continue editing data..
        /// </summary>
        internal static string Confirmation_Reset
        {
            get
            {
                return ResourceManager.GetString("Confirmation_Reset", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to reset layout? Reopen this view for the new layout to take effect..
        /// </summary>
        internal static string Confirmation_ResetLayout
        {
            get
            {
                return ResourceManager.GetString("Confirmation_ResetLayout", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you want to save changes?.
        /// </summary>
        internal static string Confirmation_Save
        {
            get
            {
                return ResourceManager.GetString("Confirmation_Save", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на You need to save the parent {0} entity before adding a new record. Do you want to save it now?.
        /// </summary>
        internal static string Confirmation_SaveParent
        {
            get
            {
                return ResourceManager.GetString("Confirmation_SaveParent", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на  *.
        /// </summary>
        internal static string Entity_Changed
        {
            get
            {
                return ResourceManager.GetString("Entity_Changed", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на  (New).
        /// </summary>
        internal static string Entity_New
        {
            get
            {
                return ResourceManager.GetString("Entity_New", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на DataService Request Error.
        /// </summary>
        internal static string Exception_DataServiceRequestErrorCaption
        {
            get
            {
                return ResourceManager.GetString("Exception_DataServiceRequestErrorCaption", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Update Error.
        /// </summary>
        internal static string Exception_UpdateErrorCaption
        {
            get
            {
                return ResourceManager.GetString("Exception_UpdateErrorCaption", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Validation Error.
        /// </summary>
        internal static string Exception_ValidationErrorCaption
        {
            get
            {
                return ResourceManager.GetString("Exception_ValidationErrorCaption", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning.
        /// </summary>
        internal static string Warning_Caption
        {
            get
            {
                return ResourceManager.GetString("Warning_Caption", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Some fields contain invalid data. Click OK to close the page and lose unsaved changes. Press Cancel to continue editing data..
        /// </summary>
        internal static string Warning_SomeFieldsContainInvalidData
        {
            get
            {
                return ResourceManager.GetString("Warning_SomeFieldsContainInvalidData", resourceCulture);
            }
        }
    }
}
